global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: resource-booking-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - resource-booking-app:8080
